version: '3'

services: 
    app:
        image: mateusob/node-pfa-1
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        command: bash -c "node index.js"
        networks:
            - node-mysql-network
            - node-nginx-network
        tty: true
        depends_on:
            - db

    nginx:
        image: mateusob/nginx-node
        container_name: nginx
        restart: always
        networks: 
            - node-nginx-network
        ports: 
            - "8000:80"
        depends_on:
            - app

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./dbdata:/var/lib/mysql
            - ./scripts/course_modules.sql:/docker-entrypoint-initdb.d/01.sql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - node-mysql-network

networks: 
    node-mysql-network:
        driver: bridge
    node-nginx-network:
        driver: bridge
